import asyncio
from playwright.async_api import async_playwright

client = openai.OpenAI()


async def execute_browser_action(command: str):
    try:
        # Use OpenAI's GPT model to process the command
        response = client.completions.create(
            model="text-davinci-003",
            prompt=f"Generate Playwright script for the following command: {command}",
            max_tokens=150,
        )
        action_script = response.choices[0].text.strip()

        # Validate the generated script (basic validation example)
        if not action_script.startswith("await"):
            raise ValueError("Invalid script generated by OpenAI")

        # Execute the generated script using Playwright
        async with async_playwright() as p:
            browser = await p.chromium.launch()
            page = await browser.new_page()
            await page.goto("https://example.com")  # Replace with the initial URL

            # Execute the commands from the action_script
            exec(action_script)

            await page.screenshot(path="screenshot.png")
            await browser.close()

            return "Command executed successfully"
    except openai.OpenAIError as e:
        raise ValueError(f"Error communicating with OpenAI: {str(e)}")
    except Exception as e:
        raise ValueError(f"Error executing browser action: {str(e)}")


if __name__ == "__main__":
    command = "navigate to amazon.com and add first laptop with 4 stars to my cart"
    asyncio.run(execute_browser_action(command))
